pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:8.0'
            args '-u root:root'
        }
    }

    environment {
        PROJECT_PATH = 'WebApplicationTest/WebApplicationTest'
        PUBLISH_DIR = 'publish'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mohammadhasani669/test-repo.git'
            }
        }
        stage('Restore') {
            steps {
                dir("${PROJECT_PATH}") {
                    sh 'dotnet restore'
                }
            }
        }
        stage('Build') {
            steps {
                dir("${PROJECT_PATH}") {
                    sh 'dotnet build --configuration Release'
                }
            }
        }
        stage('Publish') {
            steps {
                dir("${PROJECT_PATH}") {
                    sh "dotnet publish -c Release -o ${PUBLISH_DIR}"
                }
            }
        }
    }
}
